name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  step1:
    name: Download and Install Essentials
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

  step2:
    name: Log In to AnyDesk
    runs-on: windows-latest
    needs: step1  # Waits for step1 to complete
    steps:
      - name: Log In To AnyDesk
        run: cmd /c show.bat

  step3:
    name: Run Time Counter
    runs-on: windows-latest
    needs: step2  # Waits for step2 to complete
    steps:
      - name: Time Counter
        run: python time.py